apiVersion: v1
kind: Secret
metadata:
  name: doc-research-secret
  namespace: doc-research-lab
type: Opaque
stringData:
  LLM_BASE_URL: "${LLM_BASE_URL}"
  LLM_API_KEY: "${LLM_API_KEY}"
  EMBEDDING_BASE_URL: "${EMBEDDING_BASE_URL}"
  EMBEDDING_API_KEY: "${EMBEDDING_API_KEY}"
  PGVECTOR_USER: "${PGVECTOR_USER}"
  PGVECTOR_PASSWORD: "${PGVECTOR_PASSWORD}"
